### ISSUE TITLE
Make turbo syntax enhancements a bit more visually explicit

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/overpass-turbo#250]
Some people still confuse turbo extensions with actual Overpass API syntax. To make this a bit clearer, I propose a somewhat different coloring for mustache blocks. Instead of just highlighting the curly braces, the whole block should be rendered in a different color (except for `{{style: ... }}`), maybe even in a different background color.

Here's how that might look like:

![turbo](https://cloud.githubusercontent.com/assets/5842757/16207012/5d928fc2-372b-11e6-90ee-c1b59f6eaee1.png)

Coloring is probably still a bit distracting and not ideal, I just used it for testing.

``` CSS
.cm-mustache {
  color: blue;
  background-color: #fcfcfc;
  font-weight: lighter;
}
```

...inspired by https://codemirror.net/demo/mustache.html
