### ISSUE TITLE
MapCSS: Support for `tag is not null`

### ISSUE THREAD

**Issue by tordans** [tyrasd/overpass-turbo#544]
The Wizard allows to check the presence of a tag, regardless of its value
```css
bicycle is null
```

Which becomes … in overpass
```css
way["bicycle"!~".*"]({{bbox}});
```

However, it looks like there is no way to use the same syntax in an MapCSS definition. The given example return an error message. Adding quotation marks does not help either.
```css
{{style:
way[bicycle!~.*] {
  color: red;
}
}}
```

**Comment by simon04** [comment]
The following style should do the trick:

```css
{{style:
way[!bicycle] {
  color: red;
}
}}
```
